#!/bin/zsh

set -eo pipefail

repos=("interop-be-agreement-email-sender"
    "interop-be-agreement-management"
    "interop-be-agreement-process"
    "interop-be-agreement-readmodel-writer"
    "interop-be-anac-certified-attributes-importer"
    "interop-be-api-gateway"
    "interop-be-attribute-registry-management"
    "interop-be-attribute-registry-process"
    "interop-be-attribute-registry-readmodel-writer"
    "interop-be-attributes-loader"
    "interop-be-authorization-management"
    "interop-be-authorization-process"
    "interop-be-authorization-server"
    "interop-be-authorization-updater"
    "interop-be-backend-for-frontend"
    "interop-be-catalog-management"
    "interop-be-catalog-process"
    "interop-be-catalog-readmodel-writer"
    "interop-be-certified-mail-sender"
    "interop-be-dashboard-metrics-report-generator"
    "interop-be-datalake-data-export"
    "interop-be-dtd-catalog-exporter"
    "interop-be-dtd-catalog-total-load-exporter"
    "interop-be-dtd-metrics"
    "interop-be-eservice-descriptors-archiver"
    "interop-be-eservices-monitoring-exporter"
    "interop-be-ivass-certified-attributes-importer"
    "interop-be-metrics-report-generator"
    "interop-be-notifier"
    "interop-be-notifier-seeder"
    "interop-be-one-trust-notices"
    "interop-be-padigitale-report-generator"
    "interop-be-party-management"
    "interop-be-party-mock-registry"
    "interop-be-party-process"
    "interop-be-party-registry-proxy"
    "interop-be-pn-consumers"
    "interop-be-privacy-notices-updater"
    "interop-be-purpose-management"
    "interop-be-purpose-process"
    "interop-be-purpose-readmodel-writer"
    "interop-be-purposes-archiver"
    "interop-be-selfcare-onboarding-consumer"
    "interop-be-tenant-management"
    "interop-be-tenant-process"
    "interop-be-tenant-readmodel-writer"
    "interop-be-tenants-attributes-checker"
    "interop-be-tenants-cert-attr-updater"
    "interop-be-token-details-persister"
    "interop-debezium-postgresql"
    "interop-frontend")

for repo in ${repos[@]}; do
  ./terraform.sh import dev "aws_ecr_repository.app[\"$repo\"]" "$repo"
done;

