apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: gh-runners-trigger-auth
  namespace: gh-runners
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: gh-pat
      key: GITHUB_PAT
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: interop-testing-gh-runners-scaled-object
  namespace: gh-runners
spec:
  scaleTargetRef:
    name: interop-testing-gh-runners
  minReplicaCount: 0
  maxReplicaCount: 15
  pollingInterval: 15
  triggers:
  - type: github-runner
    authenticationRef:
      name: gh-runners-trigger-auth
    metadata:
      githubApiURL: "https://api.github.com"
      enableEtags: "true"
      owner: "micdes-pagopa"
      runnerScope: "repo"
      repos: "interop-testing-gh-runners"
      noDefaultLabels: "true"
      labels: "self-hosted,micdes-pagopa/interop-testing-gh-runners"
      targetWorkflowQueueLength: "1"
  - type: cron
    metadata:
      timezone: Europe/Rome
      start: 0 8 * * 1-5
      end: 0 20 * * 1-5
      desiredReplicas: "3"
