name: "Terraform Plan"

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
      - '!master'   # excludes master
    paths:
      - 'src/main/**'
      - '.github/workflows/*.yml'

defaults:
  run:
    shell: bash
    working-directory: src/main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    strategy:
      matrix:
        environment: [dev_ro, test_ro, prod_ro]
    name: "terraform-plan"
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Configure AWS Credentials
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Read terraform version
        id: read-version
        working-directory: src/
        run: |
          echo "TERRAFORM_VERSION=`cat ./.terraform-version`" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Plan (main)
        id: plan_main
        run: |
          ./terraform.sh plan ${{ matrix.environment }}

      - name: Terraform Plan (K8s)
        id: plan_k8s
        working-directory: src/main/k8s
        run: |
          ./terraform.sh plan ${{ matrix.environment }}
